### ISSUE TITLE
[FEATURE] Enhancing the UI of the cards in the home screen

### ISSUE THREAD

**Issue by jaivsh** [bhattabhi013/Vritant#73]
### Description

The UI of cards in home screen looks simplistic and basic. I'd enhance the UI capabilities of cards in this section, so that they become more eye-catching and better in-sync with the rest of the app's UI.

### Screenshots

![Screenshot_20230730_081356](https://github.com/bhattabhi013/Vritant/assets/93859359/162483a8-f0ee-4a63-abac-ea55b7d574da)

**Comment by jaivsh** [comment]
@bhattabhi013 please assign me this!

**Comment by bhattabhi013** [comment]
Hi @jaivsh,
Can you please share the design first?

**Comment by jaivsh** [comment]
> Hi @jaivsh,
> Can you please share the design first?
![Screenshot_20230801_180843](https://github.com/bhattabhi013/Vritant/assets/93859359/ec604ff6-058d-4564-a0fa-69d6e2e127ec)

![Screenshot_20230801_180706](https://github.com/bhattabhi013/Vritant/assets/93859359/c8d0aba2-00b9-4137-b73c-b6483f2e3b5b)

**Comment by jaivsh** [comment]
@bhattabhi013 i've uploaded the screenshots of changed UIs

**Comment by bhattabhi013** [comment]
Hi,
This looks good but can you remove color from the header?
Also, Can you remove the bg-color form the cards and add some box-shadow on it? (refer ss)
<img width="575" alt="image" src="https://github.com/bhattabhi013/Vritant/assets/47862474/30d2eaaa-968a-4206-8543-7715809cf28c">

You can decrease the width of the cards so that card's properties don't overlap
<img width="524" alt="image" src="https://github.com/bhattabhi013/Vritant/assets/47862474/66bea030-ac9f-46a7-be7d-4573fb49474d">

**Comment by jaivsh** [comment]
@bhattabhi013 please assign!

**Comment by jaivsh** [comment]
@bhattabhi013 also, can you please assign this one?

**Comment by bhattabhi013** [comment]
Assigning it to you @jaivsh
